### ISSUE TITLE
UnconnectedHighway validator broken in some cities

### ISSUE THREAD

**Issue by Rub21** [osmlab/osmlint#218]
The error  :point_down:

```13 tiles processed in 2s
/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:16
fer(this.argGeom,this.distance)}catch(t){if(!(t instanceof l))throw t;this.sav
                                                                    ^
TypeError: object is not a function
    at bn.e.computeDepths (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:13:3857)
    at ki.e.computeNodeDepth (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:15:16265)
    at ki.e.computeDepths (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:15:17033)
    at ki.e.computeDepth (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:15:16544)
    at Qi.e.buildSubgraphs (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:16:4244)
    at Qi.e.buffer (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:16:5176)
    at sr.e.bufferOriginalPrecision (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:16:14650)
    at sr.e.computeGeometry (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:16:14289)
    at sr.e.getResultGeometry (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:16:14813)
    at Function.sr.bufferOp (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:16:15077)
    at St.e.buffer (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:19:28373)```

**Comment by Rub21** [comment]
```
13 tiles processed in 2s
/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:16
fer(this.argGeom,this.distance)}catch(t){if(!(t instanceof l))throw t;this.sav
                                                                    ^
TypeError: object is not a function
    at bn.e.computeDepths (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:13:3857)
    at ki.e.computeNodeDepth (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:15:16265)
    at ki.e.computeDepths (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:15:17033)
    at ki.e.computeDepth (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:15:16544)
    at Qi.e.buildSubgraphs (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:16:4244)
    at Qi.e.buffer (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:16:5176)
    at sr.e.bufferOriginalPrecision (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:16:14650)
    at sr.e.computeGeometry (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:16:14289)
    at sr.e.getResultGeometry (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:16:14813)
    at Function.sr.bufferOp (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:16:15077)
    at St.e.buffer (/usr/local/src/app/osmlint/node_modules/turf/node_modules/turf-buffer/node_modules/jsts/dist/jsts.min.js:19:28373)
46 tiles processed in 30m 58s^C

```

**Comment by Rub21** [comment]
### Crossing highways and buildings
https://github.com/osmlab/osmlint/tree/master/validators/crossingHighwaysBuildings
```
Starting up 4 workers... Job started.
Processing tile coords from "osm" source.
1691 tiles processed in 4s
/home/ruben/apps/osmlint/node_modules/jsts/dist/jsts.min.js:9
},getDimension:function(){return 1},reverse:function(){for(var t=this.geometries.length,e=new Array(t).fill(null),n=0;n<this.geometries.length;n++)e[t-1-n]=this.geometries[n].reverse();return this.getFactory().createMultiLineString(e)},getBoundary:function(){return new dt(this).getBoundary()},getGeometryType:function(){return"MultiLineString"},copy:function(){for(var t=new Array(this.geometries.length).fill(null),e=0;e<t.length;e++)t[e]=this.geometries[e].copy();return new gt(t,this.factory)},interfaces_:function(){return[st]},getClass:function(){return gt}}),gt.serialVersionUID=0x7155d2ab4afa8000,e(dt.prototype,{boundaryMultiLineString:function(t){if(this.geom.isEmpty())return this.getEmptyMultiPoint();var e=this.computeBoundaryCoordinates(t);return 1===e.length?this.geomFact.createPoint(e[0]):this.geomFact.createMultiPointFromCoords(e)},getBoundary:function(){return this.geom instanceof St?this.boundaryLineString(this.geom):this.geom instanceof
[object Object]
2576 tiles processed in 7sevents.js:163
      throw er; // Unhandled 'error' event
      ^

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:562:16)
    at handleTile (/home/ruben/apps/osmlint/node_modules/@mapbox/tile-reduce/src/index.js:131:23)
    at DestroyableTransform.handleZXYLine (/home/ruben/apps/osmlint/node_modules/@mapbox/tile-reduce/src/index.js:148:5)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:191:7)
    at DestroyableTransform.Readable.read (/home/ruben/apps/osmlint/node_modules/readable-stream/lib/_stream_readable.js:386:26)
    at flow (/home/ruben/apps/osmlint/node_modules/readable-stream/lib/_stream_readable.js:734:34)
    at resume_ (/home/ruben/apps/osmlint/node_modules/readable-stream/lib/_stream_readable.js:717:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
