### ISSUE TITLE
error running overlaphighways linter

### ISSUE THREAD

**Issue by maning** [osmlab/osmlint#271]
Running from latest master of overlaphighways linters I get error 👇 

```

230 tiles processed in 1s/Users/maning/projects/git/osmlint/node_modules/@turf/turf/turf.js:179
    if (!isNumber(coordinates[0]) || !isNumber(coordinates[1])) throw new Error('coordinates must contain numbers');
                                                                ^

Error: coordinates must contain numbers
    at Object.point (/Users/maning/projects/git/osmlint/node_modules/@turf/turf/turf.js:179:71)
    at module.exports (/Users/maning/projects/git/osmlint/validators/overlapHighways/map.js:130:40)
    at gotData (/Users/maning/projects/git/osmlint/node_modules/@mapbox/tile-reduce/src/worker.js:68:5)
    at notify (/Users/maning/projects/git/osmlint/node_modules/queue-async/build/queue.js:62:29)
    at /Users/maning/projects/git/osmlint/node_modules/queue-async/build/queue.js:49:29
    at tileUnzipped (/Users/maning/projects/git/osmlint/node_modules/@mapbox/tile-reduce/src/mbtiles.js:38:7)
    at Unzip.onEnd (zlib.js:227:5)
    at emitNone (events.js:91:20)
    at Unzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
254 tiles processed in 1sevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:584:16)
    at handleTile (/Users/maning/projects/git/osmlint/node_modules/@mapbox/tile-reduce/src/index.js:131:23)
    at DestroyableTransform.handleZXYLine (/Users/maning/projects/git/osmlint/node_modules/@mapbox/tile-reduce/src/index.js:148:5)
    at emitOne (events.js:96:13)
    at DestroyableTransform.emit (events.js:188:7)
    at addChunk (/Users/maning/projects/git/osmlint/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/Users/maning/projects/git/osmlint/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/Users/maning/projects/git/osmlint/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (/Users/maning/projects/git/osmlint/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at DestroyableTransform.write [as _transform] (/Users/maning/projects/git/osmlint/node_modules/binary-split/index.js:24:14)
```

**Comment by Rub21** [comment]
@maning you should use 
- node: v6.12.3
- npm : 3.10.10

Those mostly come with nvm.

**Comment by maning** [comment]
Tried again, I get an output but process did not finish.  Same issue as above.
However, the output doesn't seem to be overlapping highways.
See https://gist.github.com/maning/3f421f7bf1d07c47e36affc5d7637501
